name: send-newsletter
on:
  push:
    branches:
      - master
jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    environment: newsletter
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/get_domain.sh
        shell: bash
        id: site-domain
      - run: ./.github/workflows/commit-date.sh
        shell: bash
        id: commit-date
      - name: Render newsletter
        uses: ./.github/actions/render-newsletter
        with:
          posts_dir: "./_posts"
          template_path: "./.github/workflows/newsletter_template.html"
          sendgrid_list_id: "559adb5e-7164-4ac8-bbb5-1398d4ff0df9"
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          suppression_group_id: 17889
          sendgrid_sender_id: 2072506
          site_yaml: "./_config.yml"
          subject_format: "[Code for Boston] %s"
          slack_url: ${{ secrets.SLACK_URL }}
          after_date: ${{ steps.commit-date.outputs.commit-date }}
          context: >-
            {
            "domain": "${{ steps.site-domain.outputs.domain }}"
            }
