name: send-newsletter
on: push
jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    environment: newsletter
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/get_domain.sh
        shell: bash
        id: site-domain
      - run: ./.github/workflows/find-modified-newsletter.sh
        shell: bash
        id: newsletter-path
      - uses: ./.github/actions/render-newsletter
        if: ${{ steps.newsletter-path.outputs.post_path != '' }}
        with:
          text_path: "${{ steps.newsletter-path.outputs.post_path }}"
          template_path: "./.github/workflows/newsletter_template.html"
          sendgrid_list_id: "559adb5e-7164-4ac8-bbb5-1398d4ff0df9"
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          suppression_group_id: 17889
          site_yaml: "./_config.yml"
          context: >-
            {
            "domain": "${{ steps.site-domain.outputs.domain }}"
            }
